name: Build and Push Frontend Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name : env create
        run: echo "${{secrets.ENV}}" >> .env
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-blogpost:latest

  deploy:
  needs: build-and-push
  runs-on: ubuntu-latest
  environment: ${{ github.ref }}
  
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Cloud SDK and kubectl
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'gke-gcloud-auth-plugin kubectl'
        export_default_credentials: true

    - name: Configure kubectl to use cluster-dev
      run: |
        gcloud container clusters get-credentials cluster-dev \
          --region ${{ secrets.GKE_REGION }} \
          --project ${{ secrets.GCP_PROJECT_ID }}
        kubectl cluster-info

    - name: Deploy to GKE (update blog-frontend image)
      run: |
        kubectl set image deployment/blog-frontend frontend=${{ secrets.DOCKERHUB_USERNAME }}/frontend-blogpost:latest
        kubectl rollout status deployment/blog-frontend


