name: Build and Push Frontend Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name : env create
        run: echo "${{secrets.ENV}}" >> .env
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-blogpost:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ github.ref }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
  
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
  
      - name: Install gke-gcloud-auth-plugin
        run: |
          # Baixa a versão mais recente do plugin diretamente do Google Cloud Storage
          PLUGIN_URL="https://storage.googleapis.com/cloud-sdk-release/google-cloud-cli-$(gcloud --version | grep 'Google Cloud SDK' | awk '{print $4}')-linux-x86_64.tar.gz"
          curl -O $PLUGIN_URL
          tar -xzf google-cloud-cli-*-linux-x86_64.tar.gz
          sudo cp google-cloud-sdk/bin/gke-gcloud-auth-plugin /usr/local/bin/
          sudo chmod +x /usr/local/bin/gke-gcloud-auth-plugin
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV
  
      - name: Configure kubectl to use cluster-dev
        run: |
          gcloud container clusters get-credentials cluster-dev \
            --region ${{ secrets.GKE_REGION }} \
            --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl cluster-info
  
      - name: Deploy to GKE (update blog-frontend image)
        run: |
          kubectl set image deployment/blog-frontend frontend=${{ secrets.DOCKERHUB_USERNAME }}/frontend-blogpost:latest
          kubectl rollout status deployment/blog-frontend
